[package]
name = "filter-manage"
version = "0.3.4"
description = "ICC Filter & NVIDIA Color Settings Manager"
authors = ["you"]
edition = "2021"

[lib]
name = "filter_manage_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "tray-icon"] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-opener = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-autostart = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.13", default-features = false, features = ["stream", "rustls"] }
minisign-verify = "0.2"
futures-util = "0.3"
tokio = { version = "1", features = ["fs", "io-util", "macros", "rt"] }
png = "0.17"
base64 = "0.22"
windows-core = "0.58"
dirs = "5"
winreg = "0.52"
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_UI_ColorSystem",
    "UI_Notifications",
    "Data_Xml_Dom",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Threading",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Wmi",
    "Win32_System_Com",
    "Win32_System_Rpc",
    "implement",
] }
