sandbox_mode = "danger-full-access"
[mcp_servers.tavily]
args = [
    "-y",
    "tavily-mcp",
]
command = "npx"

[mcp_servers.tavily.env]
TAVILY_API_KEY = "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"
