/**
 * Material Symbols → react-icons/md 映射表
 *
 * 将 Google Material Symbols 图标名映射到 react-icons 的 Material Design 图标组件。
 * 默认使用 Outlined 变体，filled 为 Filled 变体。
 */

import {
  MdAdd,
  MdAddPhotoAlternate,
  MdAutoAwesome,
  MdCheck,
  MdCheckCircle,
  MdClose,
  MdCode,
  MdDarkMode,
  MdDelete,
  MdDownload,
  MdEdit,
  MdEditNote,
  MdExpandMore,
  MdFolderOpen,
  MdHelp,
  MdInfo,
  MdKeyboard,
  MdKeyboardArrowDown,
  MdLanguage,
  MdLightMode,
  MdLogout,
  MdMonitor,
  MdInsights,
  MdMovie,
  MdMusicNote,
  MdNotifications,
  MdOpenInNew,
  MdPalette,
  MdPhotoCamera,
  MdPowerSettingsNew,
  MdRadioButtonUnchecked,
  MdRefresh,
  MdRestartAlt,
  MdRule,
  MdSave,
  MdSearch,
  MdSettings,
  MdSettingsBackupRestore,
  MdSettingsBrightness,
  MdSportsEsports,
  MdSystemUpdate,
  MdTerminal,
  MdTune,
  MdUpload,
  MdUploadFile,
  MdVisibility,
  // Outlined 变体
  MdOutlineAdd,
  MdOutlineAddPhotoAlternate,
  MdOutlineAutoAwesome,
  MdOutlineCheck,
  MdOutlineCheckCircle,
  MdOutlineClose,
  MdOutlineCode,
  MdOutlineDarkMode,
  MdOutlineDelete,
  MdOutlineDownload,
  MdOutlineEdit,
  MdOutlineEditNote,
  MdOutlineExpandMore,
  MdOutlineFolderOpen,
  MdOutlineHelp,
  MdOutlineInfo,
  MdOutlineKeyboard,
  MdOutlineKeyboardArrowDown,
  MdOutlineLanguage,
  MdOutlineLightMode,
  MdOutlineLogout,
  MdOutlineMonitor,
  MdOutlineMovie,
  MdOutlineMusicNote,
  MdOutlineNotifications,
  MdOutlineOpenInNew,
  MdOutlinePalette,
  MdOutlinePhotoCamera,
  MdOutlinePowerSettingsNew,
  MdOutlineRadioButtonUnchecked,
  MdOutlineRefresh,
  MdOutlineRestartAlt,
  MdOutlineRule,
  MdOutlineSave,
  MdOutlineSearch,
  MdOutlineSettings,
  MdOutlineSettingsBackupRestore,
  MdOutlineSettingsBrightness,
  MdOutlineSportsEsports,
  MdOutlineSystemUpdate,
  MdOutlineTerminal,
  MdOutlineTune,
  MdOutlineUpload,
  MdOutlineUploadFile,
  MdOutlineVisibility,
} from "react-icons/md";
import type { IconType } from "react-icons";

/**
 * 图标映射条目：outlined (默认) + filled 两个变体
 */
interface IconEntry {
  outlined: IconType;
  filled: IconType;
}

/**
 * Material Symbols 图标名 → react-icons 组件映射
 *
 * 键名即为原来在 <span class="material-symbols-outlined">xxx</span> 中使用的名称
 */
export const iconMap: Record<string, IconEntry> = {
  add: { outlined: MdOutlineAdd, filled: MdAdd },
  add_photo_alternate: { outlined: MdOutlineAddPhotoAlternate, filled: MdAddPhotoAlternate },
  check: { outlined: MdOutlineCheck, filled: MdCheck },
  check_circle: { outlined: MdOutlineCheckCircle, filled: MdCheckCircle },
  close: { outlined: MdOutlineClose, filled: MdClose },
  delete: { outlined: MdOutlineDelete, filled: MdDelete },
  download: { outlined: MdOutlineDownload, filled: MdDownload },
  edit: { outlined: MdOutlineEdit, filled: MdEdit },
  expand_more: { outlined: MdOutlineExpandMore, filled: MdExpandMore },
  folder_open: { outlined: MdOutlineFolderOpen, filled: MdFolderOpen },
  help: { outlined: MdOutlineHelp, filled: MdHelp },
  info: { outlined: MdOutlineInfo, filled: MdInfo },
  keyboard: { outlined: MdOutlineKeyboard, filled: MdKeyboard },
  keyboard_arrow_down: { outlined: MdOutlineKeyboardArrowDown, filled: MdKeyboardArrowDown },
  language: { outlined: MdOutlineLanguage, filled: MdLanguage },
  logout: { outlined: MdOutlineLogout, filled: MdLogout },
  monitor: { outlined: MdOutlineMonitor, filled: MdMonitor },
  monitoring: { outlined: MdOutlineNotifications, filled: MdInsights },
  notifications: { outlined: MdOutlineNotifications, filled: MdNotifications },
  open_in_new: { outlined: MdOutlineOpenInNew, filled: MdOpenInNew },
  palette: { outlined: MdOutlinePalette, filled: MdPalette },
  power_settings_new: { outlined: MdOutlinePowerSettingsNew, filled: MdPowerSettingsNew },
  radio_button_unchecked: { outlined: MdOutlineRadioButtonUnchecked, filled: MdRadioButtonUnchecked },
  refresh: { outlined: MdOutlineRefresh, filled: MdRefresh },
  restart_alt: { outlined: MdOutlineRestartAlt, filled: MdRestartAlt },
  rule: { outlined: MdOutlineRule, filled: MdRule },
  save: { outlined: MdOutlineSave, filled: MdSave },
  search: { outlined: MdOutlineSearch, filled: MdSearch },
  settings: { outlined: MdOutlineSettings, filled: MdSettings },
  settings_backup_restore: { outlined: MdOutlineSettingsBackupRestore, filled: MdSettingsBackupRestore },
  system_update: { outlined: MdOutlineSystemUpdate, filled: MdSystemUpdate },
  terminal: { outlined: MdOutlineTerminal, filled: MdTerminal },
  upload: { outlined: MdOutlineUpload, filled: MdUpload },
  upload_file: { outlined: MdOutlineUploadFile, filled: MdUploadFile },
  // 新增图标
  light_mode: { outlined: MdOutlineLightMode, filled: MdLightMode },
  dark_mode: { outlined: MdOutlineDarkMode, filled: MdDarkMode },
  settings_brightness: { outlined: MdOutlineSettingsBrightness, filled: MdSettingsBrightness },
  movie: { outlined: MdOutlineMovie, filled: MdMovie },
  sports_esports: { outlined: MdOutlineSportsEsports, filled: MdSportsEsports },
  edit_note: { outlined: MdOutlineEditNote, filled: MdEditNote },
  photo_camera: { outlined: MdOutlinePhotoCamera, filled: MdPhotoCamera },
  code: { outlined: MdOutlineCode, filled: MdCode },
  music_note: { outlined: MdOutlineMusicNote, filled: MdMusicNote },
  visibility: { outlined: MdOutlineVisibility, filled: MdVisibility },
  auto_awesome: { outlined: MdOutlineAutoAwesome, filled: MdAutoAwesome },
  tune: { outlined: MdOutlineTune, filled: MdTune },
};
